<!-- START: One Poster Template -->
<div class="poster-card">
    <div class="poster-info">
        <div class="poster-title-wrapper">
            <a class="poster-title clean-url">Title Here</a>
        </div>
        

        <div class="poster-tags">
            <div class="tag">Action</div>
            <div class="tag">Fantasy</div>
            <div class="tag">Drama</div>
        </div>

        <div class="poster-details">
            <div class="poster-date">Jan. 20, 2021</div>
            <!-- ie. air date -->
            <div class="poster-count">24ep</div>
            <!-- ie. number of episodes -->
            <div class="poster-length">23min/ep</div>
            <!-- ie. episode length -->
        </div>
    </div>

    <div class="poster-main">
        <div class="poster-img">
            <a href="">
                <img
                    src=""
                    alt="Image Here"
                />
            </a>
        </div>

        <div class="poster-main-content-wrapper">
            <div class="poster-additional-info">
                <div class="poster-studio">Newish's Studio</div>
                <div class="poster-source">Light Novel</div>
                <div class="poster-themes">
                    <div class="tag">School</div>
                    <div class="tag">Military</div>
                    <div class="tag">Demons</div>
                </div>
            </div>

            <div class="poster-description">
                content here. content here. content here. content here. content
                here. content here. content here. content here. content here.
                content here. content here. content here. content here. content
                here. content here. content here. content here. content here.
                content here. content here. content here.
            </div>
        </div>
        <div class="poster-score fa-solid fa-star"> 9.12</div>
    </div>
</div>
<!-- END: One Poster Template -->
